config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :photos
  resources :albums
  resources :fortunes

  root 'homepages#home'

  resources :homepages do
  end

  resources :students do
    resources :courses
  end

  resources :albums do
    resources :photos do
      collection do
        get 'search'
      end

      member do
        get 'preview'
      end
    end
  end
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :student
end

app/models/fortune.rb
class Fortune < ApplicationRecord

  def self.generate_seed
    Fortune.create(fortune: %s(Today it's up to you to create the peacefulness you long for.), source: " rails generate resource fortune fortune:string source:string")
    Fortune.create(fortune: %s(A friend asks only for your time not your money.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(If you refuse to accept anything but the best, you very often get it.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(A smile is your passport into the hearts of others.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(A good way to keep healthy is to eat more Chinese food.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Your high-minded principles spell success.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Hard work pays off in the future, laziness pays off now.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Change can hurt, but it leads a path to something better.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Enjoy the good luck a companion brings you.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(People are naturally attracted to you.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Hidden in a valley beside an open stream- This will be the type of place where you will find your dream.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(A chance meeting opens new doors to success and friendship.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(You learn from your mistakes... You will learn a lot today.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(If you have something good in your life, don't let it go!), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(What ever you're goal is in life, embrace it visualize it, and for it will be yours.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Your shoes will make you happy today.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(You cannot love life until you live the life you love.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Be on the lookout for coming events; They cast their shadows beforehand.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Land is always on the mind of a flying bird.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(The man or woman you desire feels the same about you.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Meeting adversity well is the source of your strength.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(A dream you have will come true.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Our deeds determine us, as much as we determine our deeds.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(Never give up. You're not a failure if you don't give up.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(You will become great if you believe in yourself.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(There is no greater pleasure than seeing your loved ones prosper.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(You will marry your lover.), source: "http://www.fortunecookiemessage.com/archive.php")
    Fortune.create(fortune: %s(A very attractive person has a message for you.), source: "http://www.fortunecookiemessage.com/archive.php")
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :album
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :courses
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    log params.inspect
    @albums = Album.all
  end

  def show
    log params.inspect
    @album = Album.find(params[:id])
  end

  def new
    log params.inspect
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def album_params
    params.require(:album).permit(:title)
  end


end

app/controllers/application_controller.rb
require 'colorize'
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def log str
    logger.info "**** ".red
    logger.info "**** ".red + str
    logger.info "**** ".red
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def show
    log params.inspect
    student_id = params[:student_id]
    courses_id = params[:id]
    @student = Student.find(student_id.to_i)
    @course = @student.courses.where(id: courses_id).first
  end
end

app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
  def index
    @fortunes = Fortune.all
  end

  def show
    @fortune = helpers.get_fortune(params[:id])
  end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  def index
    log params.inspect
    render html: "<strong>Index Action in Homepage</strong>".html_safe
  end

  def show
    log params.inspect
    render html: "<strong>Show Action in Homepage</strong>".html_safe
  end

  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    log params.inspect
    render html: "<strong>Index Action in Photos<strong>".html_safe
  end

  def show
    log params.inspect
    render html: "<strong>Show Action in Photos</strong>".html_safe
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/fortunes_helper.rb
module FortunesHelper

  def is_number? string
    true if Float(string) rescue false
  end

  def get_fortune(param)
    if is_number? param
      Fortune.find(param)
    elsif param == "random"
      Fortune.offset(rand(Fortune.count)).first
    else
      nil
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :album_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/index.html.erb
<h1>All Photo Albums</h1>

<% @albums.each do |a| %>
  <p>
    <%= a.title %>
  </p>
<% end %>

app/views/albums/new.html.erb
<h1>New Photo Album</h1>

<%= render 'form', album: @album %>

<p>
  <%= link_to 'Back', albums_path %>
</p>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/courses/show.html.erb
<h1>Course Info</h1>

<p>Student: <%= @student.name %> is registered for this course:
  <p><%= @course.name %>
  </p>
</p>

app/views/fortunes/index.html.erb
<h1>All fortunes, Ever</h1>
  <% @fortunes.each do |f| %>
    <p>
      <%= f.fortune %>
    </p>
  <% end %>

app/views/fortunes/show.html.erb
<h1>Fortune</h1>

<% if @fortune.nil? %>
  <p>Sorry no fortune for you today!</p>
<% else %>
  <p>Thanks for asking for your fortune from the cyber fortune teller. Here's your fortune!</p>
  <h2>"<%= @fortune.fortune %>"</h2>
<% end %>

app/views/homepages/home.html.erb
<h1>Home Page Sweet Home Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Controllersdemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>